{
 "title": "Jitsi Stats",
 "description": "Dashboard for stats gathered by 3rd party exporter karrieretutor/jitsi-prom-exporter",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "jvb_instance",
    "query": "label_values(jitsi_jvb_largest_conference{job = \"jitsi\"}, host)"
   },
   {
    "name": "jicofo_instance",
    "query": "label_values(jitsi_jicofo_bridge_count{job = \"jitsi\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Conferences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_conferences{host=~\"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jitsi_jvb_largest_conference) "
    }
   ]
  },
  {
   "title": "Data Channels Sent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_data_channel_messages_sent{host =~ \"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "RX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_bytes_received{host=~\"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "Conference seconds",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_conference_seconds{host =~ \"$jvb_instance\"}) "
    }
   ]
  },
  {
   "title": "Daily Average Conference Duration",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(jitsi_jvb_total_conference_seconds{host =~ \"$jvb_instance\"}[1d])) / sum(increase(jitsi_jvb_total_conferences_completed{host =~ \"$jvb_instance\"}[1d]))"
    }
   ]
  },
  {
   "title": "Failed Conferences",
   "type": "singlestat",
   "description": "The total number of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_failed_conferences{host =~ \"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "No payload channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 1 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_no_payload_channels{host =~ \"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "Heath Monitor",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Healthy" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_health_status{host =~ \"$jvb_instance\"}",
     "legendFormat": "JVB {{host}}"
    },
    {
     "expr": "jitsi_jicofo_health_status{host =~ \"$jicofo_instance\"}",
     "legendFormat": "JICOFO {{host}}"
    },
    {
     "expr": "up{job=\"jitsi\"}",
     "legendFormat": "JPE"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_participants{host=~\"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "Largest Conference Ever",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(jitsi_jvb_largest_conference{host=~\"$jvb_instance\"}) "
    }
   ]
  },
  {
   "title": "Data Channel Received",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_data_channel_messages_received{host =~ \"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "TX Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 3 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_bytes_sent{host =~ \"$jvb_instance\"})",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "Completed Conferences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_conferences_completed{host =~ \"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "Created Conferences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_conferences_created{host =~ \"$jvb_instance\"})"
    }
   ]
  },
  {
   "title": "Partially Failed Conferences",
   "type": "singlestat",
   "description": "The total number of partially failed conferences on the bridge. A conference is marked as partially failed when some of its channels has failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 3 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_partially_failed_conferences{host =~ \"$jvb_instance\"})",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  {
   "title": "No transport channels",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 3 },
   "format": "short",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jvb_total_no_transport_channels{host =~ \"$jvb_instance\"})",
     "legendFormat": "{{ CPU }}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Conference Sizes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_jvb_conference_sizes{host=~\"$jvb_instance\"}) by(conferenceSize)",
     "legendFormat": "{{conferenceSize}} "
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_threads{host =~ \"$jvb_instance\"}"
    }
   ]
  },
  {
   "title": "Conferences by Video Senders",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_jvb_conferences_by_video_senders{host=~\"$jvb_instance\"}) by(conferenceSize)",
     "legendFormat": "{{conferenceSize}} "
    }
   ]
  },
  {
   "title": "RTT aggregate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_rtt_aggregate{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Jitter aggregate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_jitter_aggregate{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Conferences by Audio Senders",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_jvb_conferences_by_audio_senders{host=~\"$jvb_instance\"}) by(conferenceSize)",
     "legendFormat": "{{conferenceSize}} "
    }
   ]
  },
  {
   "title": "Bitrate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_bit_rate_download{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Datachannel messages received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jitsi_jvb_total_data_channel_messages_received{host =~ \"$jvb_instance\"}[1h])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Video streams",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_videostreams{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_jvb_conferences{host=~\"$jvb_instance\"}) by(host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bitrate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_bit_rate_upload{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Datachannel messages sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jitsi_jvb_total_data_channel_messages_sent{host =~ \"$jvb_instance\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Video Channels",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_videochannels{host=~\"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_participants{host=~\"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Loss-degraded participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jitsi_jvb_total_loss_degraded_participant_seconds{host =~ \"$jvb_instance\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Loss-limited participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jitsi_jvb_total_loss_limited_participant_seconds{host =~ \"$jvb_instance\"}[5m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Loss rate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_loss_rate_upload{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Loss rate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_loss_rate_download{host =~ \"$jvb_instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Loss-controlled participant seconds",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jitsi_jvb_total_loss_controlled_participant_seconds{host =~ \"$jvb_instance\"}[5m])",
     "legendFormat": "time"
    }
   ]
  },
  {
   "title": "Bytes received",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_jvb_total_bytes_received{host =~ \"$jvb_instance\"}[1h])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Packet rate upload",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_packet_rate_upload{host =~ \"$jvb_instance\"}",
     "legendFormat": " {{host}}"
    }
   ]
  },
  {
   "title": "Packet rate download",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jitsi_jvb_packet_rate_download{host =~ \"$jvb_instance\"}",
     "legendFormat": "Packets: {{host}}"
    }
   ]
  },
  {
   "title": "Largest Conference",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jitsi_jvb_largest_conference{host=~\"$jvb_instance\"}) ",
     "legendFormat": "Largest Conference"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(jitsi_jvb_total_bytes_sent{host =~ \"$jvb_instance\"}[1h])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Jicofo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Video Bridges",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_bridge_count{})"
    }
   ]
  },
  {
   "title": "Largest Conference Current",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jitsi_jicofo_largest_conference{host=~\"$jicofo_instance\"})"
    }
   ]
  },
  {
   "title": "Conferences Created",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 35 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_total_conferences_created{host=~\"$jicofo_instance\"})"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_conferences{host=~\"$jicofo_instance\"})"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jitsi_jicofo_conferences{host=~\"$jicofo_instance\"}",
     "legendFormat": "conferences"
    }
   ]
  },
  {
   "title": "Jicofo Group Size Distribution",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_conference_sizes{host=~\"$jicofo_instance\"}) by(conferenceSize)",
     "legendFormat": "{{conferenceSize}} "
    }
   ]
  },
  {
   "title": "Operational Video Bridges",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_operational_bridge_count{})"
    }
   ]
  },
  {
   "title": "Largest Conference Ever",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 37 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(jitsi_jicofo_largest_conference{host=~\"$jicofo_instance\"})"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_total_participants{host=~\"$jicofo_instance\"})"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jitsi_jicofo_participants{host=~\"$jicofo_instance\"})"
    }
   ]
  }
 ]
}